apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: tasks
spec:
  ingressClassName: nginx
  rules:
    - host: tasks.local
      http:
        paths:
          # Ruch do API — bardziej szczegółowe ścieżki muszą być przed "/"
          - path: /tasks
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
          - path: /health
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 80
          - path: /ready
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 80
          - path: /metrics
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 80
          # Cały pozostały ruch idzie do frontendu
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
