apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: tasks
  annotations:
    # Wskazuje że używamy nginx jako ingress controllera
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: tasks.local    # lokalny hostname 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
