apiVersion: v1
kind: Service
metadata:
  name: postgres        # ta nazwa = adres DNS wewnątrz klastra: postgres.tasks.svc.cluster.local
  namespace: tasks
spec:
  # ClusterIP — dostępny tylko wewnątrz klastra, nie wystawiony na zewnątrz
  type: ClusterIP
  selector:
    app: postgres       # kieruje ruch do podów z etykietą app=postgres
  ports:
    - port: 5432
      targetPort: 5432
