apiVersion: v1
kind: Secret
metadata:
  name: tasks-secret
  namespace: tasks
type: Opaque
# stringData — wpisujemy wartości jako zwykły tekst, K8s sam zakoduje do base64
stringData:
  DB_PASSWORD: "devpassword"
